### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by SigPloiter** [samyak24jain/FuzzyCMeans#1]
hello man, just wanted to know what is tp, tn, fp, fn represents

thanks

**Comment by samyak24jain** [comment]
Hello @SigPloiter, 
tp = true positives
tn = true negatives
fp = false positives
fn = false negatives
Refer to [this link](https://en.wikipedia.org/wiki/Confusion_matrix) for the explanations of these.
Hope this helps!
