### ISSUE TITLE
TypeError: 'zip' object is not subscriptable

### ISSUE THREAD

**Issue by hadhila** [samyak24jain/FuzzyCMeans#4]
Traceback (most recent call last):
  File "fuzzy.py", line 135, in <module>
    labels, centers = fuzzyCMeansClustering()
  File "fuzzy.py", line 127, in fuzzyCMeansClustering
    cluster_centers = calculateClusterCenter(membership_mat)
  File "fuzzy.py", line 89, in calculateClusterCenter
    x = list(cluster_mem_val[j])
TypeError: 'zip' object is not subscriptable

**Comment by hadhila** [comment]
can anyone please tell me how to find solution to this error as soon as possible

**Comment by shimafoolad** [comment]
In Python 2, zip returned a list. In Python 3, zip returns an iterable object. 
you can use (in python 3):

`x=next(cluster_mem_val)`

instead of (in python 2):

`x = list(cluster_mem_val[j])`

refer to "https://stackoverflow.com/questions/27431390/typeerror-zip-object-is-not-subscriptable"

**Comment by ggafiled** [comment]
TypeError: 'zip' object is not subscriptable
I try next(cluster_mem_val) it still error 
I run on python 3.7

Can anyone tell me how to fix this error
Thank you.

**Comment by theimageprocessingguy** [comment]
I made the code to work. Just make the following changes:
Change line 84: cluster_mem_val = list(zip(*membership_mat))
Change line 105: distances = [np.linalg.norm(list(map(operator.sub, x, cluster_centers[j]))) for j in range(k)]
After these the code must run smoothly. :)

**Comment by geesoon** [comment]
Hi. After following the change suggested by @theimageprocessingguy I still get the following error.
![image](https://user-images.githubusercontent.com/36831396/86480602-e691cd80-bd80-11ea-94dc-5c3263a3450d.png)

Can somebody help debugging this? Thanks for the help in advance!

**Comment by theimageprocessingguy** [comment]
> Hi. After following the change suggested by @theimageprocessingguy I still get the following error.
> ![image](https://user-images.githubusercontent.com/36831396/86480602-e691cd80-bd80-11ea-94dc-5c3263a3450d.png)
> 
> Can somebody help debugging this? Thanks for the help in advance!

@geesoon It has been a long time since I used this code and the changes worked for me at that time. I will check the code again and let you know when its done. As an alternative, I have also created a github repository on Fuzzy C Means using numpy library whose link is provided below:

[Fuzzy-C-Means-Python](https://github.com/theimageprocessingguy/Fuzzy-C-Means-Python) 

Please check the link and reply if it works for you. Happy coding!!

**Comment by OmerTurann** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.
AbhishekGit-hash, @DonOndeje, @aur42, @Zagal435, @rahXephonz, @crescenity, @danielgcp, @kijun, @seoparson, @devhindo, @INNOVASE, @fantasticit, @jackson-sandland, @JellyT01, @ritesh-guaubox, @zhajingzhaxi, @shipengtaov, @JClackett, @yenkuanlee, @Fooooooooooox
